/**
 * Root Layout Component (Presentation Layer)
 * 
 * This file serves as the root layout component in our Next.js application, representing
 * the outermost layer of the UI in our clean architecture implementation. It belongs to
 * the presentation/UI layer, handling the global layout structure, theme management,
 * and font configuration.
 * 
 * In clean architecture terms, this component:
 * - Lives in the outermost layer (Interface Adapters/Presentation)
 * - Contains no business logic
 * - Focuses purely on UI concerns (layout, theming, fonts)
 * - Provides the foundational structure for all other UI components
 */

import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/app/_components/utils';
import { ThemeProvider } from './_components/theme-provider';
import { Toaster } from './_components/ui/sonner';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen font-sans antialiased flex items-center justify-center',
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
